// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-9EwLB2ZKLe8NixGyy4NxqWwLiaRxYTM',
    appId: '1:851500300170:web:44c57e46de9c4b0c47fa73',
    messagingSenderId: '851500300170',
    projectId: 'background-users',
    authDomain: 'background-users.firebaseapp.com',
    storageBucket: 'background-users.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEuUVdyuL2LW59iZOA2DvpW0lEhzEpMaY',
    appId: '1:851500300170:android:f97ddf7da2acc7de47fa73',
    messagingSenderId: '851500300170',
    projectId: 'background-users',
    storageBucket: 'background-users.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBy1VRRBotn0KCcbnRZcgO6KHBxj0AzLk',
    appId: '1:851500300170:ios:3e6a2e37add21e6447fa73',
    messagingSenderId: '851500300170',
    projectId: 'background-users',
    storageBucket: 'background-users.appspot.com',
    iosClientId: '851500300170-3sq5ohbq9laqk6r8frk8htn3mj5vh20l.apps.googleusercontent.com',
    iosBundleId: 'com.example.backgroundUsers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBy1VRRBotn0KCcbnRZcgO6KHBxj0AzLk',
    appId: '1:851500300170:ios:3e6a2e37add21e6447fa73',
    messagingSenderId: '851500300170',
    projectId: 'background-users',
    storageBucket: 'background-users.appspot.com',
    iosClientId: '851500300170-3sq5ohbq9laqk6r8frk8htn3mj5vh20l.apps.googleusercontent.com',
    iosBundleId: 'com.example.backgroundUsers',
  );
}
